ANNOTATIONS = "assets/goldrels.jsonl"
SC_TOK2VEC_CONFIG = "configs/sc_tok2vec.cfg"
SC_TL_TOK2VEC_CONFIG = "configs/sc_TL_tok2vec.cfg"
SC_TRF_CONFIG = "configs/sc_trf.cfg"
SC_TL_TRF_CONFIG = "configs/sc_TL_trf.cfg"
SC_TRAIN_FILE = "scdata/train.spacy"
SC_DEV_FILE = "scdata/dev.spacy"
SC_TEST_FILE = "scdata/test.spacy"
SC_TRAINED_MODEL = "sctraining/model-best"

REL_TOK2VEC_CONFIG = "configs/rel_tok2vec.cfg"
REL_TL_TOK2VEC_CONFIG = "configs/rel_TL_tok2vec.cfg"
REL_TRF_CONFIG = "configs/rel_trf.cfg"
REL_TL_TRF_CONFIG = "configs/rel_TL_trf.cfg"
REL_TRAIN_FILE = "reldata/train.spacy"
REL_DEV_FILE = "reldata/dev.spacy"
REL_TEST_FILE = "reldata/test.spacy"
REL_TRAINED_MODEL = "reltraining/model-best"